baseURL = "http://mfthmhmmd.github.io/"
languageCode = "en-us"
title = "mfthmhmmd pages"
theme = "kiss"

[params.social]
twitter = "mfthmhmmd"
github = "mfthmhmmd"
email = "mfthmhmmd@gmail.com"
linkedin = "miftah-muhammad"

[params.social.config]
platforms = ["github","twitter","email","linkedin"]

